### ISSUE TITLE
Getting and error while running ./install.sh

### ISSUE THREAD

**Issue by ecolesgap** [andresgap/coconut#7]
/coconut$ ./install.sh

==========  Welcome to Coconut  ==========
· Coconut is a friendy Gem to dinamically change the configurations of your project.

• Remove previous version

• Installing coconut

- Running bundle install
Note:  cmd: bundle install
You have one or more invalid gemspecs that need to be fixed.
The gemspec at /home/user/coconut/coconut.gemspec is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo URL here." is not a valid HTTP URI'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    "TODO: Put your gem's website or public repo URL here." is not a valid HTTP URI

- Installing gem
Note:  cmd: gem install ./
ERROR:  Could not find a valid gem './' (>= 0) in any repository
✖ Something happens and coconut wasn't installed

• Setting coconut configuration
./install.sh: line 81: coconut: command not found
✔ Coconut was successfully setted up
♥ Happy Coding!

**Comment by aradiquez** [comment]
+1 happening to me as well 

also to be able to avoid some bash like problems, you can add at the top of the `install.sh` file the following line: 
```
#!/bin/bash
```

**Comment by royGap** [comment]
Fix for this issue
https://github.com/andresgap/coconut/pull/8
